name: Daily workflows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"  # Daily at noon EST

jobs:

  run-daily-tests:
    uses: ./.github/workflows/testing.yml

  notify:
    runs-on: ubuntu-latest
    needs: [run-daily-tests]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
    - uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465  # TSL
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Leifer Lab to NWB Daily Failure
        to: cody.c.baker.phd@gmail.com
        from: Leifer Lab to NWB
        body: "The daily workflow for Leifer Lab to NWB failed: please check status at https://github.com/CatalystNeuro/leifer-lab-to-nwb/actions/workflows/dailies.yml"
