name: Deploy tests

on:
  pull_request:

concurrency:  # Cancel previous workflows on the same pull request
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  DevTests:
    uses: catalystneuro/leifer-lab-to-nwb/.github/workflows/testing_dev.yml@main
